CREATE DATABASE ATIVIDADE

USE ATIVIDADE

CREATE TABLE PESSOA(
	PES_INT_ID INT NOT NULL IDENTITY (1,1),
	PES_STR_NOME VARCHAR (70) NOT NULL,
	PES_STR_CPF CHAR (11) NOT NULL,
	PES_STR_END VARCHAR (70) NOT NULL
	CONSTRAINT PES_INT_ID PRIMARY KEY (PES_INT_ID),
	CONSTRAINT PES_STR_CPF UNIQUE (PES_STR_CPF),
	CONSTRAINT PES_STR_END UNIQUE (PES_STR_END)
);

CREATE TABLE PACIENTE(
	PAC_INT_ID INT NOT NULL IDENTITY (1,1),
	CONSTRAINT PAC_INT_ID PRIMARY KEY (PAC_INT_ID),
	CONSTRAINT PES_INT_ID FOREIGN KEY (PES_INT_ID)
    REFERENCES PESSOA(PES_INT_ID)
);

CREATE TABLE MEDICO(
	MED_INT_ID INT NOT NULL IDENTITY (1,1),
	MED_STR_CRM VARCHAR (06) NOT NULL,
	FOREIGN KEY (PAC_INT_ID)
	REFERENCES PACIENTE (PAC_INT_ID)
);

CREATE TABLE ENDERECO(
	END_INT_ID INT NOT NULL IDENTITY (1,1),
	END_STR_RUA VARCHAR (70) NOT NULL,
	END_INT_NUM INT NOT NULL
);

CREATE TABLE ESTADO(
	EST_INT_ID INT NOT NULL IDENTITY (1,1),
	EST_STR_SIG CHAR (06) NOT NULL,
	CONSTRAINT EST_INT_ID PRIMARY KEY(EST_INT_ID),
	CONSTRAINT EST_STR_SIG UNIQUE(EST_STR_SIG),
)

CREATE TABLE CIDADE(
	CID_INT_ID INT NOT NULL IDENTITY (1,1),
	CID_STR_SIG CHAR (02) NOT NULL
	FOREIGN KEY (EST_INT_ID) 
	REFERENCES ESTADO (EST_INT_ID)
)
