CREATE DATABASE HOSPITAL;
 
USE HOSPITAL;
 
CREATE TABLE MEDICO(
	MED_INT_ID INT NOT NULL IDENTITY (1,1) ,
	MED_STR_NOME VARCHAR (70) NOT NULL,
	MED_STR_CPF CHAR (11) NOT NULL,
	CONSTRAINT PK_MEDICO_ID PRIMARY KEY(MED_INT_ID),
	CONSTRAINT UK_MEDICO_CPF UNIQUE(MED_STR_CPF),
)
 
CREATE TABLE PACIENTE (
	PAC_INT_ID INT NOT NULL IDENTITY (1,1),
	PAC_STR_NOME VARCHAR (70) NOT NULL,
	PAC_STR_CPF CHAR (11) NOT NULL,
	CONSTRAINT PK_PACIENTE_ID PRIMARY KEY(PAC_INT_ID),
	CONSTRAINT UK_PACIENTE_CPF UNIQUE (PAC_STR_CPF)
)
 
CREATE TABLE CONSULTA (
	CON_INT_ID INT NOT NULL IDENTITY (1,1),
	PAC_INT_ID INT,
	MED_INT_ID INT,
	CONSTRAINT PK_CONSULTA_ID PRIMARY KEY (CON_INT_ID),
	CONSTRAINT FK_CONSULTA_PAC_ID FOREIGN KEY (PAC_INT_ID) REFERENCES PACIENTE (PAC_INT_ID),
	CONSTRAINT FK_CONSULTA_MED_ID FOREIGN KEY (MED_INT_ID) REFERENCES MEDICO (MED_INT_ID)
)
 
CREATE TABLE MEDICAMENTO (
	 MEC_INT_ID INT NOT NULL IDENTITY(1,1),
	 MEC_STR_DESCRICAO VARCHAR (70) NOT NULL,
	 MEC_STR_CODBARRAS VARCHAR (70) NOT NULL
	 CONSTRAINT PK_MEDICAMENTO_ID PRIMARY KEY (MEC_INT_ID),
	 CONSTRAINT UK_MEDICAMENTO_CODBARRAS UNIQUE (MEC_STR_CODBARRAS)
)
 
CREATE TABLE RECEITA(
	CON_INT_ID INT NOT NULL,
	MEC_INT_ID INT NOT NULL,
	CONSTRAINT FK_RECEITA_MEDICAMENTO_ID FOREIGN KEY (MEC_INT_ID) REFERENCES MEDICAMENTO (MEC_INT_ID),
	CONSTRAINT FK_RECEITA_CONSULTA_ID FOREIGN KEY (CON_INT_ID) REFERENCES CONSULTA (CON_INT_ID),
)
 
--DML
 
--INSERT, UPDATE E DELETE
 
INSERT INTO MEDICO (MED_STR_NOME, MED_STR_CPF) VALUES ('NOME','11111111111');
 
INSERT INTO MEDICO (MED_STR_NOME, MED_STR_CPF) VALUES ('GABRIEL','20145678955');
 
DROP DATABASE HOSPITAL;
 
CREATE DATABASE HOSPITAL;
 
USE HOSPITAL;
 
CREATE TABLE MEDICO(
	MED_INT_ID INT NOT NULL IDENTITY (1,1) ,
	MED_STR_NOME VARCHAR (70) NOT NULL,
	MED_STR_CPF CHAR (11) NOT NULL,
	CONSTRAINT PK_MEDICO_ID PRIMARY KEY(MED_INT_ID),
	CONSTRAINT UK_MEDICO_CPF UNIQUE(MED_STR_CPF),
)
 
CREATE TABLE PACIENTE (
	PAC_INT_ID INT NOT NULL IDENTITY (1,1),
	PAC_STR_NOME VARCHAR (70) NOT NULL,
	PAC_STR_CPF CHAR (11) NOT NULL,
	CONSTRAINT PK_PACIENTE_ID PRIMARY KEY(PAC_INT_ID),
	CONSTRAINT UK_PACIENTE_CPF UNIQUE (PAC_STR_CPF)
)
 
CREATE TABLE CONSULTA (
	CON_INT_ID INT NOT NULL IDENTITY (1,1),
	PAC_INT_ID INT,
	MED_INT_ID INT,
	CONSTRAINT PK_CONSULTA_ID PRIMARY KEY (CON_INT_ID),
	CONSTRAINT FK_CONSULTA_PAC_ID FOREIGN KEY (PAC_INT_ID) REFERENCES PACIENTE (PAC_INT_ID),
	CONSTRAINT FK_CONSULTA_MED_ID FOREIGN KEY (MED_INT_ID) REFERENCES MEDICO (MED_INT_ID)
)
 
 
CREATE TABLE MEDICAMENTO (
	 MEC_INT_ID INT NOT NULL IDENTITY(1,1),
	 MEC_STR_NOME VARCHAR (70) NOT NULL,
	 MEC_STR_DESCRICAO VARCHAR (70) NOT NULL,
	 MEC_STR_CODBARRAS VARCHAR (70) NOT NULL
	 CONSTRAINT PK_MEDICAMENTO_ID PRIMARY KEY (MEC_INT_ID),
	 CONSTRAINT UK_MEDICAMENTO_CODBARRAS UNIQUE (MEC_STR_CODBARRAS)
)
 
ALTER TABLE CONSULTA
ADD CONSTRAINT FK_CONSULTA_MEC_ID FOREIGN KEY (MEC_INT_ID) REFERENCES MEDICAMENTO (MEC_INT_ID)
 
ALTER TABLE CONSULTA
ADD CONSTRAINT FK_CONSULTA_MEC_ID
FOREIGN KEY (MEC_INT_ID)
REFERENCES MEDICAMENTO (MEC_INT_ID);
 
SELECT * FROM MEDICAMENTO
 
CREATE TABLE RECEITA(
	CON_INT_ID INT NOT NULL,
	MEC_INT_ID INT NOT NULL,
	CONSTRAINT FK_RECEITA_MEDICAMENTO_ID FOREIGN KEY (MEC_INT_ID) REFERENCES MEDICAMENTO (MEC_INT_ID),
	CONSTRAINT FK_RECEITA_CONSULTA_ID FOREIGN KEY (CON_INT_ID) REFERENCES CONSULTA (CON_INT_ID),
)
 
--DML
 
--INSERT, UPDATE E DELETE
 
INSERT INTO MEDICO (MED_STR_NOME, MED_STR_CPF) VALUES ('AMORIM','11111111111');
 
INSERT INTO MEDICO (MED_STR_NOME, MED_STR_CPF) VALUES ('GABRIEL','20145678955');
 
INSERT INTO MEDICO (MED_STR_NOME, MED_STR_CPF) VALUES ('FABGODDAM','12457756454');
 
INSERT INTO MEDICO (MED_STR_NOME, MED_STR_CPF) VALUES ('ERICK','89540840884');
 
SELECT * FROM MEDICO
 
INSERT INTO PACIENTE(PAC_STR_NOME, PAC_STR_CPF) VALUES ('RONALDO FENOMENO','12936194438');
 
INSERT INTO PACIENTE(PAC_STR_NOME, PAC_STR_CPF) VALUES ('ROMERO','75445425865');
 
INSERT INTO PACIENTE(PAC_STR_NOME, PAC_STR_CPF) VALUES ('CASSIO','00788557217');
 
SELECT * FROM PACIENTE
 
INSERT INTO MEDICAMENTO (MEC_STR_DESCRICAO, MEC_STR_CODBARRAS) VALUES ('DORIL', '12345');
 
INSERT INTO MEDICAMENTO (MEC_STR_DESCRICAO, MEC_STR_CODBARRAS) VALUES ('DIPIRONA', '13254');

 
-- INSERÇÃO EM CONSULTA
 
INSERT INTO CONSULTA (MED_INT_ID, PAC_INT_ID) VALUES (2,3)
 
INSERT INTO CONSULTA (MED_INT_ID, PAC_INT_ID) VALUES (2,1)
 
INSERT INTO CONSULTA (MED_INT_ID, PAC_INT_ID, MEC_INT_ID) VALUES (2,1)
 
INSERT INTO CONSULTA (MED_INT_ID, PAC_INT_ID, MEC_INT_ID) VALUES (2,3)
 
SELECT * FROM CONSULTA
 
SELECT
M.MED_STR_NOME,
P.PAC_STR_NOME
FROM MEDICO AS M INNER JOIN CONSULTA AS C ON M.MED_INT_ID = C.MED_INT_ID INNER JOIN PACIENTE AS P ON P.PAC_INT_ID = C.PAC_INT_ID
 
 
--ALTERAR DADOS DE UMA TABELA
 
UPDATE MEDICO SET MED_STR_NOME = 'GABRIEL FRITAS' WHERE MED_INT_ID = 2;
 
--DELETAR DADOS DE UMA TABELA
 
DELETE FROM MEDICO WHERE MED_INT_ID = 4
 
-- TESTES INNER JOIN
 
--SELECT
--M.MED_STR_NOME AS ('MEDICO'),
--P.PAC_STR_NOME,
--R.
--MD.MEC_STR_NOME
--FROM MEDICO AS M INNER JOIN CONSULTA AS C ON M.MED_INT_ID = C.MED_INT_ID 
--INNER JOIN PACIENTE AS P ON P.PAC_INT_ID = C.PAC_INT_ID
--INNER JOIN RECEITA AS R ON R.CON_INT_ID = R.CON_INT_ID
--INNER JOIN MEDICAMENTO AS MD ON R.MEC_INT_ID = C.MED_INT_ID